# Site settings
title: Simon V.
email: semavar3@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Android & Embedded Developer
github_username:  simonvar

# Build settings
markdown: kramdown
highlighter: rouge
theme: jekyll-theme-minimal
